projectD_1/posts/urls.py
# ice_cream/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    # Главная страница
    path('', views.index, name = 'main'),
    # Страницы сообществ
    path('groups/', views.groups, name = 'groups'),

    path('group/<slug:slug>/', views.group_posts, name = 'group'),

    path('/create_post/', views.create_post, name = 'create_post')
    
    # path('group/', views.group_posts, name = 'group')

] 

projectD_1/projectD_1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
]

projectD_1/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model() 


class Group(models.Model):
    title = models.CharField(max_length=50)
    slug = models.TextField()
    description = models.TextField()

    
    def __str__(self):
        return self.title

class Post(models.Model):
    name = models.CharField(max_length=100)
    text = models.TextField()
    # Параметр on_delete=models.CASCADE обеспечивает
    #  связность данных: если из таблицы User будет удалён 
    # пользователь, то будут удалены все связанные с ним посты.
    producer = models.CharField(max_length=100)
    group = models.ForeignKey(
        Group,  
        on_delete=models.CASCADE,
        blank=True,
        null=True
    )

# class PostFavorites(models.Model):
#     name = models.CharField(max_length=100)
#     text = models.TextField()
#     pub_date = models.DateTimeField(auto_now_add=True)
#     # Параметр on_delete=models.CASCADE обеспечивает
#     #  связность данных: если из таблицы User будет удалён 
#     # пользователь, то будут удалены все связанные с ним посты.
#     producer = models.CharField(max_length=100)
#     group = models.ForeignKey(
#         Group,
#         on_delete=models.CASCADE,
#         blank=True,
#         null=True
#     )



    
    

# Пробный вариант

# class Event(models.Model):
#     name = models.CharField(max_length=200)
#     start_at = models.DateTimeField(auto_now_add=True)
#     description = models.TextField()
#     contact = models.EmailField()
#     author = models.ForeignKey(
#         User,
#         on_delete=models.CASCADE,
#         related_name="events"
#     )
#     location = models.CharField(max_length=400)

projectD_1/posts/forms.py
from .models import Post, Group
from django.forms import ModelForm, TextInput, Textarea

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['name', 'text', 'producer', 'group']
        # fields = '__all__'
        widgets = {
            "name": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Название фильма'
            }),
            "producer": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Режиссер'
            }),
            "text": Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Описание'
            }),
            # "group": TextInput(attrs={
            #     'class': 'form-control',
            #     'placeholder': 'Жанр'
            # }),
        }

projectD_1/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from .models import Post, Group
from .forms import PostForm


def index(request):
    template = 'posts/index.html'
    posts = Post.objects.order_by('-name')[:10]
    context = {
        'posts' : posts,
    }
    return render(request, template, context)

def groups(request):
    template = 'posts/group_list.html'
    group = Group.objects.order_by()[:10]
    context = {
        'groups': group,
    }
    return render(request, template, context)

def group_posts(request, slug):
    amount = int(request.GET.get("amount", 5))
    template = 'posts/posts_group_posts.html'
     # Функция get_object_or_404 получает по заданным критериям объект 
    # из базы данных или возвращает сообщение об ошибке, если объект не найден.
    # В нашем случае в переменную group будут переданы объекты модели Group,
    # поле slug у которых соответствует значению slug в запросе

    group = get_object_or_404(Group, slug=slug)
 
    # Метод .filter позволяет ограничить поиск по критериям.
    # Это аналог добавления
    # условия WHERE group_id = {group_id}
    posts = Post.objects.filter(group=group).order_by('name')[:amount]
    context = {
        'group': group,
        'posts': posts,
    }
    return render(request, template, context) 



def create_post(request):
    template = 'posts/create_post.html'
    error = ''
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('')
        else:
            error = 'Форма была неверна'


    form = PostForm()

    data = {
        'form': form,
        'error': error
    }
    return render(request, template, data)

    

projectD_1/templates/base.html
<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->
  <head>    
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> 
    <title>Лев Толстой – зеркало русской революции.</title>
  </head>
  <body>
    <header>
        {% include 'includes/header.html' %}
    </header>
    <main>
        {% block content %}
            Список постов
        {% endblock %}
    </main>
    {% comment %} <a href="{% url 'posts:groups' %}">Groups</a>
    <a href="{% url 'posts:group' %}">Group</a> {% endcomment %}
    <footer class="page-footer font-small blue border-top">
        {% include 'includes/footer.html' %}
    </footer>
  </body>
</html>

projectD_1/templates/includes/footer.html
<div class="footer-copyright text-center py-3">
    <p><span>Москва 2022</p> 
</div>  

projectD_1/templates/includes/header.html
<!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
<!-- В дальнейшем тут будет создано полноценное меню -->
{% load static %}
<nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
    <a class="navbar-brand" href="{% url 'posts:main' %}">
        Социальная сеть для любителей кино
    </a>
    <a class="navbar-brand" href="{% url 'posts:groups' %}">
        Все группы
    </a>
    <a class="navbar-brand" href="{% url 'posts:create_post' %}">
        Создать пост
      </a>
    </div>
</nav>      

projectD_1/templates/posts/create_post.html
{% extends 'base.html' %}
{% block content %}
    <div>Добавление поста</div>
    <form method="post">
        {% csrf_token %}
        {{ form.name }}<br>
        {{ form.producer }}<br>
        {{ form.text }}<br>
        <div>Жанр</div>
        {{ form.group }}<br>
        <span>{{ error }}</span>
        <button class="btn btn-success" type="submit">
            Добавить пост
        </button>
    </form>

{% endblock %} 

projectD_1/templates/posts/group_list.html
{% extends 'base.html' %}
{% block content %}
    {% for group in groups %}
    <a href="{% url 'posts:group' group.slug %}">
        <ul>
            <li>
                Название группы: {{ group.title }}
            </li>
            <li>
                Описание группы: {{ group.description }}
            </li>
        </ul>
    </a>
    
    {% endfor %} 

{% endblock %} 

projectD_1/templates/posts/index.html
{% extends 'base.html' %}
{% block content %}
  Это просто главная страница
{% endblock %} 

projectD_1/templates/posts/posts_group_posts.html
{% extends 'base.html' %}
{% block content %}
  <h1>{{ group.title }}</h1>
  {% for post in posts %}
  <ul>
    <li>
      Номер поста: {{ post.pk }}
    </li>
    <li>
      Название фильма: {{ post.name }}
    </li>
    <li>
      Режиссер: {{ post.producer }}
    </li>

  </ul>
  <p>{{ post.text }}</p>  
  {% comment %} <form method="post">
    {% csrf_token %}
    <button class="btn btn-success" type="submit">Добавить в избранное</button>
  </form> {% endcomment %}
  {% if not forloop.last %}<hr>{% endif %}
  {% endfor %} 
  <a href="{% url 'posts:create_post' %}">
    Создать пост
  </a>
{% endblock %} 